/*
  # Populate exercises table with initial data
  
  This migration adds all the exercises from the provided CSV file to the exercises table.
  
  1. Data Structure
    - Each exercise record contains:
      - module_type (category)
      - name
      - level (Beginner/Intermediate/Advanced)
      - weights for men and women
      - reps and sets
      - energy points
      
  2. Notes
    - Some exercises have NA values for weights (bodyweight exercises)
    - Cardio exercises have NA for sets
    - All text values are properly escaped
*/

-- First, let's make sure the exercises table is empty
TRUNCATE TABLE exercises RESTART IDENTITY CASCADE;

-- Now insert all the exercises
INSERT INTO exercises (module_type, name, level, men_weight, women_weight, reps, sets, energy_points) VALUES
  ('Kettlebell', 'Kettlebell Swings', 'Beginner', 12, 8, '10', 2, 2),
  ('Kettlebell', 'Goblet Squats', 'Beginner', 12, 8, '10', 2, 2),
  ('Kettlebell', 'Kettlebell Deadlifts', 'Beginner', 12, 8, '10', 2, 2),
  ('Kettlebell', 'Single Arm Kettlebell Press', 'Beginner', 8, 4, '8 per arm', 2, 3),
  ('Kettlebell', 'Kettlebell Russian Twists', 'Beginner', 8, 4, '15', 2, 3),
  ('Kettlebell', 'Kettlebell Swings', 'Intermediate', 16, 12, '15', 3, 3),
  ('Kettlebell', 'Turkish Get-Ups', 'Intermediate', 12, 8, '5 per side', 2, 5),
  ('Kettlebell', 'Kettlebell Clean and Press', 'Intermediate', 16, 12, '10 per arm', 3, 4),
  ('Kettlebell', 'Kettlebell Lunge Press', 'Intermediate', 12, 8, '10 per leg', 3, 4),
  ('Kettlebell', 'Kettlebell High Pulls', 'Intermediate', 16, 12, '12', 3, 3),
  ('Kettlebell', 'Double Kettlebell Swings', 'Advanced', 16, 12, '12', 4, 5),
  ('Kettlebell', 'Kettlebell Snatch', 'Advanced', 24, 16, '10 per arm', 4, 5),
  ('Kettlebell', 'Double Kettlebell Turkish Get-Ups', 'Advanced', 16, 12, '5', 3, 6),
  ('Kettlebell', 'Kettlebell Windmill', 'Advanced', 16, 12, '8 per side', 3, 5),
  ('Kettlebell', 'Kettlebell Complex (Swing, Clean, Squat, Press)', 'Advanced', 24, 16, '5 (each movement)', 3, 6),
  ('Body Weight', 'Bodyweight Squats', 'Beginner', NULL, NULL, '15', 2, 1),
  ('Body Weight', 'Incline Push-ups', 'Beginner', NULL, NULL, '10', 2, 2),
  ('Body Weight', 'Planks', 'Beginner', NULL, NULL, '20 seconds', 2, 2),
  ('Body Weight', 'Glute Bridges', 'Beginner', NULL, NULL, '12', 2, 1),
  ('Body Weight', 'Standing Knee Lifts', 'Beginner', NULL, NULL, '10 per leg', 2, 1),
  ('Body Weight', 'Lunges', 'Intermediate', NULL, NULL, '12 per leg', 3, 2),
  ('Body Weight', 'Standard Push-ups', 'Intermediate', NULL, NULL, '12', 3, 3),
  ('Body Weight', 'Side Planks', 'Intermediate', NULL, NULL, '30 seconds per side', 3, 3),
  ('Body Weight', 'Single Leg Glute Bridges', 'Intermediate', NULL, NULL, '10 per leg', 3, 2),
  ('Body Weight', 'Bicycle Crunches', 'Intermediate', NULL, NULL, '15 per side', 3, 3),
  ('Body Weight', 'Pistol Squats (one-legged squats)', 'Advanced', NULL, NULL, '5 per leg', 4, 5),
  ('Body Weight', 'Diamond Push-ups', 'Advanced', NULL, NULL, '15', 4, 5),
  ('Body Weight', 'Burpees', 'Advanced', NULL, NULL, '12', 4, 4),
  ('Body Weight', 'Hollow Hold', 'Advanced', NULL, NULL, '45 seconds', 4, 4),
  ('Body Weight', 'Handstand Against Wall', 'Advanced', NULL, NULL, '30 seconds', 4, 5),
  ('Resistance Band', 'Resistance Band Pull-Aparts', 'Beginner', NULL, NULL, '15', 2, 1),
  ('Resistance Band', 'Resistance Band Bicep Curls', 'Beginner', NULL, NULL, '12', 2, 1),
  ('Resistance Band', 'Resistance Band Squats', 'Beginner', NULL, NULL, '12', 2, 2),
  ('Resistance Band', 'Resistance Band Overhead Press', 'Beginner', NULL, NULL, '10', 2, 2),
  ('Resistance Band', 'Resistance Band Leg Press', 'Beginner', NULL, NULL, '12', 2, 2),
  ('Resistance Band', 'Resistance Band Chest Press', 'Intermediate', NULL, NULL, '15', 3, 3),
  ('Resistance Band', 'Resistance Band Rows', 'Intermediate', NULL, NULL, '15', 3, 3),
  ('Resistance Band', 'Resistance Band Deadlifts', 'Intermediate', NULL, NULL, '12', 3, 3),
  ('Resistance Band', 'Resistance Band Lateral Walks', 'Intermediate', NULL, NULL, '10 steps each direction', 3, 2),
  ('Resistance Band', 'Resistance Band Pallof Press', 'Intermediate', NULL, NULL, '10 per side', 3, 3),
  ('Resistance Band', 'Resistance Band Single-Leg Deadlift', 'Advanced', NULL, NULL, '10 per leg', 4, 4),
  ('Resistance Band', 'Resistance Band Pull-ups', 'Advanced', NULL, NULL, '8', 4, 5),
  ('Resistance Band', 'Resistance Band Push-Ups', 'Advanced', NULL, NULL, '15', 4, 5),
  ('Resistance Band', 'Resistance Band Woodchoppers', 'Advanced', NULL, NULL, '12 per side', 4, 4),
  ('Resistance Band', 'Resistance Band Turkish Get-Ups', 'Advanced', NULL, NULL, '5 per side', 4, 5),
  ('Dumbbell', 'Dumbbell Bicep Curls', 'Beginner', 4, 2, '12', 2, 1),
  ('Dumbbell', 'Dumbbell Shoulder Press', 'Beginner', 4, 2, '10', 2, 2),
  ('Dumbbell', 'Dumbbell Squats', 'Beginner', 6, 4, '10', 2, 2),
  ('Dumbbell', 'Dumbbell Bench Press (Flat)', 'Beginner', 6, 4, '10', 2, 2),
  ('Dumbbell', 'Dumbbell Bent Over Rows', 'Beginner', 6, 4, '12', 2, 2),
  ('Dumbbell', 'Dumbbell Lunge', 'Intermediate', 8, 6, '10 per leg', 3, 3),
  ('Dumbbell', 'Dumbbell Incline Bench Press', 'Intermediate', 10, 8, '12', 3, 3),
  ('Dumbbell', 'Dumbbell Deadlift', 'Intermediate', 10, 8, '12', 3, 3),
  ('Dumbbell', 'Dumbbell renegade Rows', 'Intermediate', 8, 6, '8 per arm', 3, 4),
  ('Dumbbell', 'Dumbbell Arnold Press', 'Intermediate', 8, 6, '10', 3, 3),
  ('Dumbbell', 'Dumbbell Snatch', 'Advanced', 16, 12, '10 per arm', 4, 5),
  ('Dumbbell', 'Dumbbell Single Leg Deadlift', 'Advanced', 16, 12, '8 per leg', 4, 5),
  ('Dumbbell', 'Dumbbell Turkish Get-Up', 'Advanced', 12, 8, '5 per side', 4, 5),
  ('Dumbbell', 'Dumbbell Thrusters', 'Advanced', 14, 10, '12', 4, 4),
  ('Dumbbell', 'Dumbbell Farmer''s Walk', 'Advanced', 20, 14, '30Mt', 4, 4),
  ('Stretching', 'Neck Side Stretch', 'Beginner', NULL, NULL, '20 sec each side', 2, 1),
  ('Stretching', 'Chest Opener', 'Beginner', NULL, NULL, '30 Sec', 2, 1),
  ('Stretching', 'Seated Hamstring Stretch', 'Beginner', NULL, NULL, '30 Sec each leg', 2, 1),
  ('Stretching', 'Cat-Cow Stretch', 'Beginner', NULL, NULL, '15 Sec per position', 5, 1),
  ('Stretching', 'Spinal Twist', 'Beginner', NULL, NULL, '20 sec each side', 2, 1),
  ('Stretching', 'Standing Quad Stretch', 'Intermediate', NULL, NULL, '30 Sec each leg', 2, 2),
  ('Stretching', 'Butterfly Stretch', 'Intermediate', NULL, NULL, '30 Sec', 2, 2),
  ('Stretching', 'Piriformis Stretch', 'Intermediate', NULL, NULL, '30 sec each side', 2, 2),
  ('Stretching', 'Kneeling Hip Flexor Stretch', 'Intermediate', NULL, NULL, '30 sec each side', 2, 2),
  ('Stretching', 'Cobra Pose', 'Intermediate', NULL, NULL, '20 Sec', 3, 2),
  ('Stretching', 'Pigeon Pose', 'Advanced', NULL, NULL, '45 sec each side', 2, 3),
  ('Stretching', 'Standing Forward Bend', 'Advanced', NULL, NULL, '45 Sec', 2, 3),
  ('Stretching', 'Camel Pose', 'Advanced', NULL, NULL, '30 Sec', 2, 3),
  ('Stretching', 'Deep Lunge with Twist', 'Advanced', NULL, NULL, '30 sec each side', 2, 3),
  ('Stretching', 'Bridge Pose', 'Advanced', NULL, NULL, '30 Sec', 2, 3),
  ('Mobility', 'Ankle Circles', 'Beginner', NULL, NULL, '20 sec each direction, each ankle', 2, 1),
  ('Mobility', 'Wrist Extension', 'Beginner', NULL, NULL, '20 sec each movement', 2, 1),
  ('Mobility', 'Shoulder Rolls', 'Beginner', NULL, NULL, '20 Sec forward, 20 sec backward', 2, 1),
  ('Mobility', 'Cat-Cow Stretch', 'Beginner', NULL, NULL, '15 sec per position', 5, 1),
  ('Mobility', 'Hip Circles', 'Beginner', NULL, NULL, '20 sec each direction', 2, 1),
  ('Mobility', 'Leg Swings', 'Intermediate', NULL, NULL, '20 swings each leg, each direction', 2, 2),
  ('Mobility', 'Arm Circles', 'Intermediate', NULL, NULL, '20 sec small circl, 20 sec largle circle', 2, 2),
  ('Mobility', 'Deep Lunge with rotation', 'Intermediate', NULL, NULL, '20 sec each side', 2, 2),
  ('Mobility', 'Thoracic Spine Windmills', 'Intermediate', NULL, NULL, '20 sec each side', 2, 2),
  ('Mobility', 'Spiderman Stretch', 'Intermediate', NULL, NULL, '30 Sec each side', 2, 2),
  ('Mobility', 'Dynamic Pigeon Pose', 'Advanced', NULL, NULL, '30 sec each side', 2, 3),
  ('Mobility', 'Bear Crawl', 'Advanced', NULL, NULL, '30 sec', 3, 3),
  ('Mobility', 'Inchworms', 'Advanced', NULL, NULL, '30 sec', 3, 3),
  ('Mobility', 'Wall Slides', 'Advanced', NULL, NULL, '20 sec', 3, 3),
  ('Mobility', 'Overhead Squat (with resistance band)', 'Advanced', NULL, NULL, '30 sec', 3, 3),
  ('Barbell', 'Barbell Squats', 'Beginner', 20, 15, '10', 2, 1),
  ('Barbell', 'Barbell Bench Press', 'Beginner', 20, 15, '10', 2, 1),
  ('Barbell', 'Barbell Rows', 'Beginner', 20, 15, '10', 2, 2),
  ('Barbell', 'Barbell Overhead Press', 'Beginner', 15, 10, '10', 2, 2),
  ('Barbell', 'Barbell Deadlift', 'Beginner', 30, 20, '10', 2, 2),
  ('Barbell', 'Barbell Front Squat', 'Intermediate', 30, 20, '10', 3, 3),
  ('Barbell', 'Barbell Incline Bench Press', 'Intermediate', 25, 18, '10', 3, 3),
  ('Barbell', 'Barbell Sumo Deadlift', 'Intermediate', 40, 30, '10', 3, 3),
  ('Barbell', 'Barbell Push Press', 'Intermediate', 25, 18, '10', 3, 3),
  ('Barbell', 'Barbell Bent over Rows (underhand grip)', 'Intermediate', 30, 20, '10', 3, 3),
  ('Barbell', 'Barbell Snatch', 'Advanced', 40, 30, '5', 4, 5),
  ('Barbell', 'Barbell Clean and Jerk', 'Advanced', 40, 30, '5', 4, 5),
  ('Barbell', 'Barbell Thruster', 'Advanced', 35, 25, '8', 4, 4),
  ('Barbell', 'Barbell Romanian deadlift', 'Advanced', 50, 40, '10', 4, 4),
  ('Barbell', 'Barbell Paused Squat', 'Advanced', 50, 40, '8', 4, 4),
  ('Isometric', 'Wall Sit', 'Beginner', NULL, NULL, '20 sec', 2, 1),
  ('Isometric', 'Planks', 'Beginner', NULL, NULL, '20 Sec', 2, 1),
  ('Isometric', 'Insometric Push-up Hold (mid-position)', 'Beginner', NULL, NULL, '10 sec', 2, 2),
  ('Isometric', 'Isometric Yogi Squat Hold', 'Beginner', NULL, NULL, '20 sec', 2, 1),
  ('Isometric', 'Static Lunge Hold', 'Beginner', NULL, NULL, '15 sec each leg', 2, 2),
  ('Isometric', 'Extended Wall Sit', 'Intermediate', NULL, NULL, '30 sec', 3, 2),
  ('Isometric', 'Extended Plank', 'Intermediate', NULL, NULL, '30 Sec', 3, 2),
  ('Isometric', 'Isometric Pull-up Hold (at top)', 'Intermediate', NULL, NULL, '10 sec', 3, 3),
  ('Isometric', 'Bridge Hold', 'Intermediate', NULL, NULL, '30 sec', 3, 2),
  ('Isometric', 'Isometric Calf Raise Hold', 'Intermediate', NULL, NULL, '30 sec', 3, 2),
  ('Isometric', 'Single -Leg Wall sit', 'Advanced', NULL, NULL, '20 sec each leg', 3, 4),
  ('Isometric', 'Side Planks', 'Advanced', NULL, NULL, '30 sec each side', 3, 3),
  ('Isometric', 'Isometric Deadlift Hold (mid-shinlevel)', 'Advanced', NULL, NULL, '15 sec', 3, 4),
  ('Isometric', 'Hanstand Hold against wall', 'Advanced', NULL, NULL, '20 sec', 3, 5),
  ('Isometric', 'Isometric Squat Hold (90 degree angle)', 'Advanced', NULL, NULL, '30 sec', 3, 4),
  ('Cardio', 'Walking', 'Beginner', NULL, NULL, '20 mi', NULL, 1),
  ('Cardio', 'Stationary Bike', 'Beginner', NULL, NULL, '15 mi', NULL, 1),
  ('Cardio', 'Eleptical Trainer', 'Beginner', NULL, NULL, '10 mi', NULL, 1),
  ('Cardio', 'Aqua Jogging', 'Beginner', NULL, NULL, '15 mi', NULL, 2),
  ('Cardio', 'Jump Rope', 'Beginner', NULL, NULL, '1 mi, 30 sec rest, repeat for 10 mi', NULL, 2),
  ('Cardio', 'Jogging', 'Intermediate', NULL, NULL, '25 mi', NULL, 2),
  ('Cardio', 'Stationary Bike', 'Intermediate', NULL, NULL, '20 mi', NULL, 3),
  ('Cardio', 'Starir Climber', 'Intermediate', NULL, NULL, '15 mi', NULL, 3),
  ('Cardio', 'Rowing Machine', 'Intermediate', NULL, NULL, '20 mi', NULL, 3),
  ('Cardio', 'High Intensity Interval Training', 'Intermediate', NULL, NULL, '20 se on, 40 sec rest, repeat for 15 mi', NULL, 4),
  ('Cardio', 'Running', 'Advanced', NULL, NULL, '30 mi +', NULL, 5),
  ('Cardio', 'Spin Class', 'Advanced', NULL, NULL, '45 mi', NULL, 5),
  ('Cardio', 'Circuit Training', 'Advanced', NULL, NULL, '30 mi', NULL, 5),
  ('Cardio', 'Tabata Workouts', 'Advanced', NULL, NULL, '4 min( 20 sec on, 10 sec rest, repeat 8 cycles)', NULL, 5),
  ('Cardio', 'Trail Running', 'Advanced', NULL, NULL, '40 mi', NULL, 5),
  ('Warm-up', 'Jumping Jacks', 'Beginner', NULL, NULL, '30 sec', 2, 1),
  ('Warm-up', 'High Knees', 'Beginner', NULL, NULL, '30 sec', 2, 1),
  ('Warm-up', 'Butt Kicks', 'Beginner', NULL, NULL, '30 sec', 2, 1),
  ('Warm-up', 'Arm Circles', 'Beginner', NULL, NULL, '30 sec', 2, 1),
  ('Warm-up', 'Leg Swings', 'Beginner', NULL, NULL, '30 sec', 2, 1),
  ('Warm-up', 'Hip Circles', 'Beginner', NULL, NULL, '30 sec', 2, 1),
  ('Warm-up', 'Torso Twists', 'Beginner', NULL, NULL, '30 sec', 2, 1),
  ('Warm-up', 'Lunges with Twist', 'Beginner', NULL, NULL, '10 per side', 2, 2),
  ('Warm-up', 'Ankle Bounces', 'Beginner', NULL, NULL, '30 sec', 2, 1),
  ('Warm-up', 'Side Shuffles', 'Beginner', NULL, NULL, '30 sec', 2, 2),
  ('Warm-up', 'Toy Soldiers', 'Beginner', NULL, NULL, '10 per leg', 2, 2),
  ('Warm-up', 'Knee Hugs', 'Beginner', NULL, NULL, '10 per leg', 2, 2),
  ('Warm-up', 'Inchworms', 'Intermediate', NULL, NULL, '10', 2, 2),
  ('Warm-up', 'Arm Swings', 'Intermediate', NULL, NULL, '30 sec', 2, 2),
  ('Warm-up', 'Shoulder Shrugs', 'Intermediate', NULL, NULL, '30 sec', 2, 2),
  ('Warm-up', 'Cat-Cow Stretch', 'Intermediate', NULL, NULL, '30 sec', 2, 2),
  ('Warm-up', 'World''s Greatest Stretch', 'Intermediate', NULL, NULL, '10 per side', 2, 3),
  ('Warm-up', 'Hamstring Stretch', 'Intermediate', NULL, NULL, '30 sec', 2, 3),
  ('Warm-up', 'Quad Stretch', 'Intermediate', NULL, NULL, '30 sec', 2, 3),
  ('Warm-up', 'Calf Stretch', 'Intermediate', NULL, NULL, '30 sec', 2, 3),
  ('Warm-up', 'Groin Stretch', 'Intermediate', NULL, NULL, '30 sec', 2, 3),
  ('Warm-up', 'Triceps Stretch', 'Intermediate', NULL, NULL, '30 sec', 2, 3),
  ('Warm-up', 'Chest Opener', 'Intermediate', NULL, NULL, '30 sec', 2, 3),
  ('Warm-up', 'Dynamic Squats', 'Intermediate', NULL, NULL, '10', 2, 3),
  ('Warm-up', 'Hip Flexor Stretch', 'Intermediate', NULL, NULL, '30 sec', 2, 3),
  ('Warm-up', 'Neck Stretch', 'Intermediate', NULL, NULL, '30 sec', 2, 3),
  ('Warm-up', 'Lat Stretch', 'Advanced', NULL, NULL, '30 sec', 2, 4),
  ('Warm-up', 'Wrist Flexor Stretch', 'Advanced', NULL, NULL, '30 sec', 2, 4),
  ('Warm-up', 'Wrist Extensor Stretch', 'Advanced', NULL, NULL, '30 sec', 2, 4),
  ('Warm-up', 'Standing Side Stretch', 'Advanced', NULL, NULL, '30 sec', 2, 4);

-- Create policy to allow all authenticated users to read exercises
DROP POLICY IF EXISTS "Authenticated users can read exercises" ON exercises;
CREATE POLICY "Authenticated users can read exercises"
  ON exercises
  FOR SELECT
  USING (true);